import express from 'express';
import { UserDataRouter } from './user-data.routes';
// import { SubscriptionTopicsRouter } from './subscription-topics.routes';
// import { UserSubscriptionRouter } from './user-subscriptions.routes';
import { LoginRouter } from './login.routes';
import { UserTrackRouter } from './user-tracks.routes';
import { AvatarRouter } from './avatars.routes';
import { FavoriteRouter } from './favorites.routes';
import { LogoutRouter } from './logout.routes';
import { InterestRouter } from './interest.routes';
import { CityRouter } from './city.routes';
import { ReferalRouter } from './referal.routes';
import { SocialMediaUpdatesRouter } from './social-media-updates.routes';
import { AroundlyPlacesRouter } from './aroundly-place.route';
import { MapsRouter } from './maps.route';
import { BusinessRouter } from './business.routes';
import { UploadRouter } from './upload.route';
import { WhatsappMessageDailyUpdatesRouter } from './whatsapp-message-daily-updates.routes';
import { CronRouter } from './cron.route';
import { InstaHandleRouter } from './insta-handle.routes';
import { PostEmbeddingsRouter } from './post-embeddings.routes';
import { UserActionsRouter } from './user-action.route';
import SourcesRouter from './sources.route';
import { WishlistRouter } from './wishlist.routes';
import { UserActionsHistoryRouter } from './user-action-history.routes';
import { AppVersionRouter } from './app-version.routes';
import { RegisterNotificationsRouter } from './register-notifications.routes';

export const routes = express.Router();

routes.use('/interest', InterestRouter);
routes.use('/user_data', UserDataRouter);
// routes.use('/subscription-topics', SubscriptionTopicsRouter);
// routes.use('/user-subscription', UserSubscriptionRouter);
routes.use('/user-action', UserActionsRouter);
routes.use('/login', LoginRouter);
routes.use('/track', UserTrackRouter);
routes.use('/avatar', AvatarRouter);
routes.use('/favorite', FavoriteRouter);
routes.use('/logout', LogoutRouter);
routes.use('/city', CityRouter);
routes.use('/refer', ReferalRouter);
routes.use('/social-media-updates', SocialMediaUpdatesRouter);
routes.use('/aroundly-places', AroundlyPlacesRouter);
routes.use('/maps', MapsRouter);
routes.use('/business', BusinessRouter);
routes.use('/upload', UploadRouter);
routes.use('/whatsapp-message', WhatsappMessageDailyUpdatesRouter);
routes.use('/cron', CronRouter);
routes.use('/insta-handle', InstaHandleRouter);
routes.use('/post-embeddings', PostEmbeddingsRouter);
routes.use('/sources', SourcesRouter);
routes.use('/wishlist', WishlistRouter);
routes.use('/user-action-history', UserActionsHistoryRouter);
routes.use('/app-version', AppVersionRouter);
routes.use('/device-notifications', RegisterNotificationsRouter);
